algorithm: 'carefl'  # in {'CAReFl', 'LRHyv', 'RECI', 'ANM'} OR in {'CAReFl', 'gp', 'linear'}
n_sims: 250

data:
  causal_mech: 'linear'  # in {linear, hoyer2009, nueralnet_l1, 'highdim'}
  n_points: 250
  seed: 0
  # only relevant for interventions
  random: true
  expected: false
  noise_dist: 'laplace'


# only relevant for flows
flow:
  architecture: 'CL'
  net_class: 'MLP'  # in {'MLP', 'ARMLP', 'MLP4'}.lower()
  nl: 2
  nh: 10
  batch_norm: false
  prior_dist: 'laplace'
  # for CL
  scale_base: true
  shift_base: true
  scale: true

anm:
  method: 'nn'

training:
  epochs: 200
  verbose: false
  split: .8
  seed: 0
  batch_size: 128


optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
  scheduler: true


